controllers/analyze_controller.py
from flask import Blueprint, render_template, request
from flask_login import current_user, login_required
from services.text_processing import analyze_text

bp = Blueprint("analyze", __name__, url_prefix="/analyze")


@bp.route("/")
@login_required
def analyze():
    text = """
    阿太为omniverse项目提供解决方案技术服务，占用着AI团队的人力。请在11月13日前进行Esign立案。
    如果没有及时立案，你就无法获得该专案对应的价值，即无法获得对应的绩效奖金。
    """
    # Gọi hàm phân tích và lưu từ mới cho người dùng hiện tại
    results = analyze_text(text, current_user)
    return render_template("analyze.html", results=results)

controllers/auth_controller.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_user, logout_user, login_required
from models import db, User
from werkzeug.security import generate_password_hash, check_password_hash

# controllers/auth_controller.py


bp = Blueprint("auth", __name__, url_prefix="/auth")

@bp.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        username = request.form["username"]
        email = request.form["email"]
        password = request.form["password"]

        # Tạo người dùng mới
        user = User(username=username, email=email)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()

        flash("Registration successful. Please log in.")
        return redirect(url_for("auth.login"))
    return render_template("register.html")


@bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]

        # Tìm người dùng trong cơ sở dữ liệu
        user = User.query.filter_by(username=username).first()

        # Nếu người dùng không tồn tại, trả về thông báo lỗi
        if user is None:
            print(f"User: {username}, Pass:{password}, Hash Pass:User not found")
            flash("Invalid username or password.")
            return render_template("login.html")

        # Kiểm tra mật khẩu nếu người dùng tồn tại
        # print(
        #     f"User: {username}, Pass:{password}, Hash Pass:\n{generate_password_hash(password)}"
        # )

        if user.check_password(password):
            login_user(user)
            return redirect(url_for("vocab.view_vocab"))

        flash("Invalid username or password.")

    return render_template("login.html")


@bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))

controllers/upload_controller.py
from flask import Blueprint, request, redirect, url_for, flash
from flask_login import current_user, login_required
from services.text_processing import process_text_file

bp = Blueprint("upload", __name__, url_prefix="/upload")


@bp.route("/file", methods=["POST"])
@login_required
def upload_file():
    if "file" not in request.files:
        flash("No file part")
        return redirect(url_for("upload.upload_page"))

    file = request.files["file"]
    if file.filename == "":
        flash("No selected file")
        return redirect(url_for("upload.upload_page"))

    # Lưu file tạm thời và xử lý
    file_path = f"/tmp/{file.filename}"
    file.save(file_path)

    # Gọi hàm process_text_file để xử lý file cho người dùng hiện tại
    results = process_text_file(file_path, current_user)

    flash("File processed successfully")
    return redirect(url_for("analyze.analyze"))

controllers/vocab_controller.py
from flask import Blueprint, redirect, render_template, url_for
from models import ExampleLink, Vocab, db, Example
from random import sample
from flask import Blueprint, redirect, url_for
from flask_login import login_required, current_user

bp = Blueprint("vocab", __name__, url_prefix="/vocab")


# controllers/vocab_controller.py
from flask import Blueprint, render_template, request
from services.text_processing import analyze_text  # Giả sử bạn có một hàm xử lý văn bản


# @bp.route("/vocab", methods=["GET", "POST"])
# def view_vocab():
#     if request.method == "POST":
#         text_input = request.form.get("text_input")
#         if text_input:
#             # Xử lý văn bản đã nhập
#             processed_text = analyze_text( text_input )  # Hàm này có thể là từ services.text_processing
#     vocab_list = Vocab.query.all()
#     return render_template("vocab.html", vocab_list=vocab_list)
@bp.before_request
def require_login():
    if not current_user.is_authenticated:
        return redirect(url_for("auth.login"))


@bp.route("/learned", methods=["GET", "POST"])
@login_required
def view_vocab_learned():
    # Truy xuất danh sách từ vựng và các ví dụ liên quan
    vocab_list = (
        Vocab.query.filter_by(user_id=current_user.id)
        .filter(Vocab.difficulty < 0)
        .options(db.joinedload(Vocab.example_links).joinedload(ExampleLink.example))
        .all()
    )
    # Chọn ngẫu nhiên 3 ví dụ nếu có hơn 3 ví dụ
    for vocab in vocab_list:
        if len(vocab.example_links) > 3:
            vocab.example_links = sample(vocab.example_links, 3)

    return render_template("vocab_mobile.html", vocab_list=vocab_list, PageTitle='Vocabulary learned')


@bp.route("/", methods=["GET", "POST"])
@login_required
def view_vocab():     
    if request.method == "POST":
        text_input = request.json.get("text_input")
        if text_input:
            print("Xử lý: " + text_input)
            # Xử lý văn bản đã nhập và thêm từ vựng cùng ví dụ
            analyze_text(text_input, current_user)

    # Truy xuất danh sách từ vựng và các ví dụ liên quan
    vocab_list = (
        Vocab.query.filter_by(user_id=current_user.id).filter(Vocab.difficulty >= 0)
        .options(db.joinedload(Vocab.example_links).joinedload(ExampleLink.example))
        .all()
    )
    # Chọn ngẫu nhiên 3 ví dụ nếu có hơn 3 ví dụ
    for vocab in vocab_list:
        if len(vocab.example_links) > 3:
            vocab.example_links = sample(vocab.example_links, 3)

    return render_template("vocab_mobile.html", vocab_list=vocab_list, PageTitle="Vocabulary")


@bp.route("/update_difficulty", methods=["POST"])
def update_difficulty():
    if request.method == "POST":
        vocab_id = request.args.get("vocab_id")
        new_difficulty = request.form.get("difficulty")
        vocab = Vocab.query.get(vocab_id)

        if vocab:
            if new_difficulty == "-2":
                # Xóa các ExampleLink liên quan trước khi xóa Example
                for example_link in vocab.example_links:
                    db.session.delete(example_link)

                db.session.commit()  # Thực hiện commit trước khi xóa Example

                # Xóa các Example
                for example_link in vocab.example_links:
                    db.session.delete(example_link.example)

                db.session.delete(vocab)  # Cuối cùng, xóa từ vựng
                db.session.commit()
                return redirect(url_for("vocab.view_vocab"))
            else:
                vocab.difficulty = int(new_difficulty)
                db.session.commit()
    return redirect(url_for("vocab.view_vocab"))


# Bạn có thể thêm một route xử lý văn bản nữa nếu cần thiết
@bp.route("/process_text", methods=["POST"])
def process_text_input():
    text_input = request.json.get("text_input")
    if text_input:
        print("Xử lý: " + text_input)
        new_words, NwordAdded = analyze_text(text_input, current_user)
        return {"Numbers of words": NwordAdded, "Words": new_words}

templates/about.html
{% extends "base.html" %}
{% block content %}

    <div class="container">
        <header>
            <h1>About WeLearn</h1>
        </header>
 
        <section class="content">
            <h2>Project Overview</h2>
            <p>
                WeLearn is a web-based platform designed to support Chinese language learning. By leveraging real-world conversations from messaging platforms like WeChat, WeLearn provides a context-driven approach for learning vocabulary, pronunciation, and sentence structure in Chinese.
            </p>

            <h2>Key Features</h2>
            <ul>
                <li><strong>Vocabulary Management:</strong> Automatically identify and store new words from conversations, along with pinyin and English translations.</li>
                <li><strong>Examples and Sentences:</strong> For each new word, WeLearn displays example sentences from real conversations, helping users understand usage in different contexts.</li>
                <li><strong>Difficulty Ratings:</strong> Users can rate the difficulty of each word, making it easier to track and prioritize learning.</li>
                <li><strong>Writing Practice:</strong> A handwriting canvas lets users practice writing Chinese characters without accidental page scrolling.</li>
                <li><strong>Progress Tracking:</strong> Track vocabulary learning progress with examples and ratings.</li>
            </ul>

            <h2>Benefits</h2>
            <p>
                WeLearn aims to provide a personalized learning experience by focusing on the vocabulary most relevant to the user’s real-life communication needs. The project not only enhances language retention but also promotes a more practical understanding of the Chinese language.
            </p>
            
            <h2>Technologies Used</h2>
            <p>
                This project is built with <strong>Flask</strong>, a Python web framework, and uses <strong>Jieba</strong> for Chinese text segmentation. The database management is handled through SQLAlchemy for secure and efficient data processing.
            </p>
        </section>

        <section>
            <h2>Technical Details</h2>
            <p><strong>Version:</strong> {{ version }}</p>
            <p><strong>Current User:</strong> {{ user|safe  if user.is_authenticated else "Guest" }}</p>
            <!-- {{user | safe }} -->
        </section>

        <footer>
            <p>&copy; 2024 WeLearn Project. All rights reserved.</p>
        </footer>
        <br/>
        <br/>
        {% if user.is_authenticated %}
            {% if user.username=='ta' %}
                <a class="btn btn-link" href="{{ url_for('updatecode') }}">updated code</a>
            {% endif %}
        {% endif %}
        <br/>
        <br/>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learn Chinese from WeChat Chats</title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- Thêm link này vào <head> của HTML -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js" integrity="sha512-fzff82+8pzHnwA1mQ0dzz9/E0B+ZRizq08yZfya66INZBz86qKTCt9MLU0NCNIgaMJCgeyhujhasnFUsYMsi0Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/hanzi-writer@3.5/dist/hanzi-writer.min.js"></script>

    <link rel='stylesheet' id='hanzi-vn-style-css' href='https://toihoctiengtrung.com/wp-content/plugins/hanzi-vn/assets/hanzi-writer-main.css' media='all' />
    <link rel='stylesheet' id='wpdiscuz-frontend-css-css' href='https://toihoctiengtrung.com/wp-content/plugins/wpdiscuz/themes/default/style.css' media='all' />
    <script src="https://toihoctiengtrung.com/wp-content/plugins/hanzi-vn/assets/hanzi-writer.min.js" id="hanzi-vn-lib-js"></script>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const navLinks = document.querySelectorAll(".nav-link");
        // Thêm sự kiện click vào mỗi liên kết để lưu trang active vào localStorage
        navLinks.forEach((link) => {
            link.addEventListener("click", function () {
                // Lưu URL của liên kết vừa bấm vào localStorage
                localStorage.setItem("activePage", this.href);
            });
        });
        // Kiểm tra và đặt lại trạng thái active từ localStorage
        const activePage = localStorage.getItem("activePage");
        if (activePage) {
            navLinks.forEach((link) => {
                // Loại bỏ lớp active
                link.classList.remove("active");
                // Kiểm tra nếu link.href khớp với trang active được lưu
                if (link.href === activePage) {
                    link.classList.add("active");
                }
            });
        }

        
    });
</script>

<style>
    body {
        background-color: #f5f5f5;
    }
 /* .nav-link.active { */
    /* color: blueviolet; */
    .navbar-light .navbar-nav .nav-link.active, 
    .navbar-light .navbar-nav .show > .nav-link {
        color: #ff5722; /* Thay bằng màu bạn muốn, ví dụ là màu cam */
    }
 /* } */

 .meaning_hide {
    display: none;
}

</style>
<!-- =============== templates\vocab_mobile.html =============================================================== -->
 
<style>
    /* Hiển thị dạng bảng trên desktop */
    @media (min-width: 768px) {
        .vocab-table {
            display: table;
            width: 100%;
        }
        .vocab-row {
            display: table-row;
        }
        .vocab-cell {
            display: table-cell;
            padding: 10px;
            vertical-align: top;
        }
    }

    /* Hiển thị dạng thẻ trên mobile */
    @media (max-width: 767px) {
        .vocab-table {
            display: block;
            width: 100%;
        }
        .vocab-row {
            display: block;
            margin-bottom: 15px;
            border: 1px solid #ddd;
            padding: 10px;
            border-radius: 5px;
        }
        .vocab-cell {
            display: block;
            padding: 5px 0;
        }
        .vocab-cell h1, .vocab-cell p {
            margin: 0;
        }
    }
</style>

<!-- Style cho input group -->
<style>
    .input-group-flex {
        display: flex;
        flex-wrap: nowrap;
        align-items: center;
    }

    .input-group-flex select {
        flex: 1;
        min-width: 150px; /* Đặt kích thước tối thiểu để không bị co lại quá nhỏ */
    }

    .input-group-flex button {
        margin-left: 5px;
        white-space: nowrap;
    }
</style>
<style>
    .BigFont {
        font-size: 40px;
        color: blue;
    }
    
    .BigFontl2 {
        font-size: 25px;
        color: rgb(92, 5, 80);
    }

</style>
<style>
/* Ẩn nút zoom */
.gmnoprint, .gm-bundled-control { 
    display: none !important;
}
</style>

<!-- ================================================================================================== -->
<!-- ================================================================================================== -->
<!-- ================================================================================================== -->
<!-- ================================================================================================== -->
<!-- ================================================================================================== -->

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">WeLearn Chinese</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!-- <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li> -->
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('vocab.view_vocab') }}">Vocabulary</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('vocab.view_vocab_learned') }}">Learned Vocabulary</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href='#' onclick="toggleMeaning()" id="an-hien-nghia">Ẩn nghĩa</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href='{{ url_for("about") }}'>About</a>
                </li>

                <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li> -->
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search Pinyin, nghĩa" aria-label="Search"  id="myInput" onkeyup="filterTable()" >
                <!-- <button class="btn btn-outline-success" type="submit">Search</button> -->
            </form>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Đăng xuất</a>
                </li>
            </ul>
        </div>

    </div>
</nav>





    {% block content %}{% endblock %}

<script>
    function removeDiacritics(text) {
        // Loại bỏ dấu trong Tiếng Việt và Pinyin của tiếng Trung
        const toneMap = {
            'ā': 'a', 'á': 'a', 'ǎ': 'a', 'à': 'a', 'ã': 'a', 'â': 'a', 'ă': 'a', 'ạ': 'a', 'ả': 'a', 'ấ': 'a', 'ầ': 'a', 'ẩ': 'a', 'ẫ': 'a', 'ậ': 'a', 'ắ': 'a', 'ằ': 'a', 'ẳ': 'a', 'ẵ': 'a', 'ặ': 'a',
            'ē': 'e', 'é': 'e', 'ě': 'e', 'è': 'e', 'ẹ': 'e', 'ẻ': 'e', 'ẽ': 'e', 'ê': 'e', 'ế': 'e', 'ề': 'e', 'ể': 'e', 'ễ': 'e', 'ệ': 'e',
            'ī': 'i', 'í': 'i', 'ǐ': 'i', 'ì': 'i', 'ị': 'i', 'ỉ': 'i', 'ĩ': 'i',
            'ō': 'o', 'ó': 'o', 'ǒ': 'o', 'ò': 'o', 'õ': 'o', 'ọ': 'o', 'ỏ': 'o', 'ô': 'o', 'ố': 'o', 'ồ': 'o', 'ổ': 'o', 'ỗ': 'o', 'ộ': 'o', 'ơ': 'o', 'ớ': 'o', 'ờ': 'o', 'ở': 'o', 'ỡ': 'o', 'ợ': 'o',
            'ū': 'u', 'ú': 'u', 'ǔ': 'u', 'ù': 'u', 'ũ': 'u', 'ụ': 'u', 'ủ': 'u', 'ư': 'u', 'ứ': 'u', 'ừ': 'u', 'ử': 'u', 'ữ': 'u', 'ự': 'u',
            'ǖ': 'ü', 'ǘ': 'ü', 'ǚ': 'ü', 'ǜ': 'ü',
            'ỳ': 'y', 'ý': 'y', 'ỷ': 'y', 'ỹ': 'y', 'ỵ': 'y',
            'đ': 'd'
        };

        return text.split('').map(char => toneMap[char] || toneMap[char.toLowerCase()] || char).join('');
    }
    function filterTable() {
    var input, filter, table, tr, td, i, txtValue;
    input = document.getElementById("myInput");
    filter = input.value.toLowerCase();
    table = document.getElementById("myTable");
    tr = table.getElementsByTagName("tr");

    for (i = 1; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[2]||tr[i].getElementsByTagName("td")[3];
        if (td) {
        txtValue = td.textContent || td.innerText;
        txtValue = removeDiacritics(txtValue);
        filter = removeDiacritics(filter);
        if (txtValue.toLowerCase().indexOf(filter) > -1) {
            tr[i].style.display = "";
        } else {
            tr[i].style.display = "none";
        }
        }
    }
    }



// Hàm ẩn hiện nghĩa của từ vựng:
function toggleMeaning() {
    const elements = document.querySelectorAll('.meaning_show');
    elements.forEach(el => {
        el.classList.toggle('meaning_hide');
    });
    
    // Cập nhật localStorage để ghi nhớ trạng thái
    const isHidden = elements[0].classList.contains('meaning_hide');
    localStorage.setItem('meaning_hidden', isHidden);
    if (isHidden) {
        document.getElementById('an-hien-nghia').innerHTML = 'Hiện nghĩa';
    } else {
        document.getElementById('an-hien-nghia').innerHTML = 'Ẩn nghĩa';
    }
}
toggleMeaning();
// Tải trạng thái từ localStorage khi trang được tải
document.addEventListener('DOMContentLoaded', () => {
    const shouldHide = localStorage.getItem('meaning_hidden') === 'true';
    if (shouldHide) {
        document.querySelectorAll('.meaning_show').forEach(el => el.classList.add('meaning_hide'));
    }
});

</script>    


<!-- Phát âm thanh: -->
<script>
    async function playSound(url) {
        try {
            const audio = new Audio(url);
            await audio.play();
        } catch (err) {
            console.error("Error playing sound:", err);
        }
    }
</script>
<!-- Phát âm thanh -->
<span id="doctu" class="" style="cursor: pointer;"><img src="/static/images/volume.png" style="height: 14px; filter: opacity(1);" alt="Phát âm" onclick="playSound('https://vtudien.com/doc/trung/电影.mp3')"></span> 
</body>
</html>

templates/vocab.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <!-- Form nhập liệu văn bản -->
<form id="vocabForm">
    <label for="text_input">Nhập đoạn văn bản tiếng Trung để phân tích và học từ mới:</label><br>
    <textarea class="form-control" id="text_input" name="text_input" rows="5" cols="50"></textarea><br>
    <button class="btn btn-primary" type="button" id="submit_button" onclick="submitForm()">Gửi văn bản</button>
    <p>Không vội vàng! Chờ 5 phút....</p>
    <p>Bấm `Gửi văn bản` xong, chờ đến khi nào app nó tự động xóa hết nội dung và hiển thị lại nội dung đã được cập nhật mới. Thời gian này App sẽ đọc từng từ 1 và gửi lên google để dịch nghĩa, nên nhanh hay chậm tùy thuộc vào số lượng từ mới và tốc độ mạng. Trung bình tầm 2-5 phút là xong.</p>
</form>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
function submitForm() {
    // Vô hiệu hóa nút gửi và thay đổi nội dung
    const submitButton = document.getElementById("submit_button");
    submitButton.textContent = "Đang xử lý...";
    submitButton.disabled = true;

    // Lấy dữ liệu từ form
    const formData = {
        text_input: document.getElementById("text_input").value
    };

    // Gửi dữ liệu bằng AJAX
    $.ajax({
        url: "{{ url_for('vocab.view_vocab') }}",
        type: "POST",
        contentType: "application/json",
        data: JSON.stringify(formData),
        success: function(response) {
            // Xử lý phản hồi từ server (hiển thị nội dung mới hoặc thông báo thành công)
            alert("Đã hoàn thành xử lý!");
            // Enable lại nút và đổi nội dung về ban đầu
            submitButton.disabled = false;
            submitButton.textContent = "Gửi văn bản";
            // Xóa nội dung của textarea
            document.getElementById("text_input").value = "";
        },
        error: function(error) {
            alert("Có lỗi xảy ra. Vui lòng thử lại.");
            // Enable lại nút và đổi nội dung về ban đầu
            submitButton.disabled = false;
            submitButton.textContent = "Gửi văn bản";
        }
    });
}
</script>


    <br/>
    <h2>{{PageTitle}}</h2>
    <table class="table" id="myTable">
        <thead>
            <tr>
                <th>STT</th>
                <th>Từ vựng</th>
                <th>Pinyin</th>
                <th>Nghĩa</th>
                <th>Ví dụ</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for vocab in vocab_list %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td><H1>{{ vocab.word }}</H1></td>
                    <td>{{ vocab.pinyin_text or "-" }}</td>
                    <td>{{ vocab.meaning or "-" }}</td>
                    <td>
                        {% for example_link in vocab.example_links %}
                            <div>
                                <p>{{ example_link.example.chinese_text }}</p>
                                <p>{{ example_link.example.pinyin_text }}</p>
                                <p>{{ example_link.example.meaning }}</p>
                            </div>
                            {% if not loop.last %}
                                <br> <!-- Thêm khoảng cách giữa các ví dụ -->
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        <form action="{{ url_for('vocab.update_difficulty', vocab_id=vocab.id) }}" method="POST">
                            <select class="form-select" name="difficulty" onchange="this.form.submit()">
                                <option value="0" {% if vocab.difficulty == 0 %}selected{% endif %}> <i class="fas fa-book-open"></i>  Chưa học đâu</option>
                                <option value="1" {% if vocab.difficulty == 1 %}selected{% endif %}> <i class="fas fa-exclamation-circle"></i> Hơi khó cần học thêm</option>
                                <option value="2" {% if vocab.difficulty == 2 %}selected{% endif %}><i class="fas fa-exclamation-triangle"></i> Rất khó cần học nhiều nữa</option>
                                <option disabled>────────────</option>
                                <option value="-1" {% if vocab.difficulty == -1 %}selected{% endif %}><i class="fas fa-check-circle"></i> Đã học xong</option>
                                <option disabled>────────────</option>
                                <option value="-2" {% if vocab.difficulty == -2 %}selected{% endif %}><i class="fas fa-trash-alt"></i> Xóa từ này</option>
                            </select>
                        </form>
                    </td>

                    <td>
                        <button class="btn btn-outline-primary" onclick="toggleWritingCanvas('{{ vocab.word }}')">Tập viết</button>
                        <button class="btn btn-outline-secondary" onclick="clearCanvas('{{ vocab.word }}')">Xóa</button>
                        <div id="writing-canvas-{{ vocab.word }}" style="display: none;">
                            <!-- Hiển thị chữ Hán gốc bằng SVG -->
                            <div class="hanzi-sample" id="hanzi-sample-{{ vocab.word }}">
                                {{ vocab.svg_data|safe }} <!-- hiển thị SVG của chữ từ dữ liệu đã crawl -->
                            </div>
                            <!-- Canvas cho phép người dùng viết tay -->
                            <canvas id="canvas-{{ vocab.word }}" width="300" height="300" style="border:1px solid #000000;"></canvas>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script>
    function toggleWritingCanvas(word) {
        const area = document.getElementById(`writing-canvas-${word}`);
        area.style.display = area.style.display === "none" ? "block" : "none";
    }
    // Hàm để xóa nội dung canvas
    function clearCanvas(word) {
        const canvas = document.getElementById(`canvas-${word}`);
        const ctx = canvas.getContext("2d");
        ctx.clearRect(0, 0, canvas.width, canvas.height);
    }
    // Code JavaScript để viết tay
    document.querySelectorAll('[id^="canvas-"]').forEach((canvas) => {
        const ctx = canvas.getContext("2d");
        let drawing = false;

        canvas.addEventListener("mousedown", (e) => startDrawing(e, ctx));
        canvas.addEventListener("mouseup", () => stopDrawing(ctx));
        canvas.addEventListener("mousemove", (e) => draw(e, ctx));

        function startDrawing(e, ctx) {
            drawing = true;
            draw(e, ctx);
        }

        function stopDrawing(ctx) {
            drawing = false;
            ctx.beginPath();
        }

        function draw(e, ctx) {
            if (!drawing) return;
            ctx.lineWidth = 5;
            ctx.lineCap = "round";
            ctx.strokeStyle = "black";
            ctx.lineTo(e.offsetX, e.offsetY);
            ctx.stroke();
            ctx.beginPath();
            ctx.moveTo(e.offsetX, e.offsetY);
        }
    });
</script>


{% endblock %}